package edu.ucaldas.ingenieria.poo.SOC.interfaz;

public class Amenaza extends javax.swing.JFrame {

   
    public Amenaza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        btnReporRedesSocial = new javax.swing.JButton();
        txtNumAtaquesRedesSocia = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        btnReporInfoConfidencial = new javax.swing.JButton();
        txtNumAtaquesInfoConfiden = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        btnReporInyecSql = new javax.swing.JButton();
        txtNumAtaquesInyecSql = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnReporRansomware = new javax.swing.JButton();
        txtNumAtaquesRanso = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        btnReporPhishin = new javax.swing.JButton();
        txtNumAtaquesPhish = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        btnReporMalware = new javax.swing.JButton();
        txtNumAtaquesMalwa = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnReporDdos = new javax.swing.JButton();
        txtNumAtaquesDdos = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        btnReporZeroDay = new javax.swing.JButton();
        txtNumAtaquesZeroDay = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        btnReporHacking = new javax.swing.JButton();
        txtNumAtaquesHacking = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        btnReporVioDatos = new javax.swing.JButton();
        txtNumAtaquesViolaDatos = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        btnReporInfraCriticas = new javax.swing.JButton();
        txtNumAtaquesInfraCriti = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jButton11 = new javax.swing.JButton();
        btnReporCibernetico = new javax.swing.JButton();
        txtNumAtaquesCiberneti = new javax.swing.JTextField();
        btnRegresarMenu = new javax.swing.JButton();
        btnRegresarMenu1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(112, 145, 255));
        jPanel1.setForeground(new java.awt.Color(112, 145, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Amenazas");

        jPanel2.setBackground(new java.awt.Color(232, 232, 232));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Ataques Redes Sociales");

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea9.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea9.setRows(5);
        jTextArea9.setText("Breaches en Facebbok, Twitter,\nAcceso no Autorizado, \nDifusión de la información falsa.");
        jScrollPane9.setViewportView(jTextArea9);

        btnReporRedesSocial.setBackground(new java.awt.Color(60, 78, 234));
        btnReporRedesSocial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporRedesSocial.setForeground(new java.awt.Color(0, 0, 0));
        btnReporRedesSocial.setText("Reportar");
        btnReporRedesSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporRedesSocialActionPerformed(evt);
            }
        });

        txtNumAtaquesRedesSocia.setBackground(new java.awt.Color(254, 43, 43));
        txtNumAtaquesRedesSocia.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtNumAtaquesRedesSocia.setForeground(new java.awt.Color(0, 0, 0));
        txtNumAtaquesRedesSocia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumAtaquesRedesSocia.setText("0");
        txtNumAtaquesRedesSocia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Ataques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumAtaquesRedesSocia.setCaretColor(new java.awt.Color(254, 43, 43));
        txtNumAtaquesRedesSocia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAtaquesRedesSociaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReporRedesSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(txtNumAtaquesRedesSocia, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane9)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporRedesSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAtaquesRedesSocia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(232, 232, 232));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Fugas Informacion Confidencial");

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea10.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea10.setRows(5);
        jTextArea10.setText("WikiLeaks, Divulgación no autorizada,\nInformacion confidencial,\nClasificada.");
        jScrollPane10.setViewportView(jTextArea10);

        btnReporInfoConfidencial.setBackground(new java.awt.Color(60, 78, 234));
        btnReporInfoConfidencial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporInfoConfidencial.setForeground(new java.awt.Color(0, 0, 0));
        btnReporInfoConfidencial.setText("Reportar");
        btnReporInfoConfidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporInfoConfidencialActionPerformed(evt);
            }
        });

        txtNumAtaquesInfoConfiden.setBackground(new java.awt.Color(254, 43, 43));
        txtNumAtaquesInfoConfiden.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtNumAtaquesInfoConfiden.setForeground(new java.awt.Color(0, 0, 0));
        txtNumAtaquesInfoConfiden.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumAtaquesInfoConfiden.setText("0");
        txtNumAtaquesInfoConfiden.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Ataques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumAtaquesInfoConfiden.setCaretColor(new java.awt.Color(254, 43, 43));
        txtNumAtaquesInfoConfiden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAtaquesInfoConfidenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnReporInfoConfidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(txtNumAtaquesInfoConfiden, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporInfoConfidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAtaquesInfoConfiden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(232, 232, 232));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Inyeccion SQL");

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea5.setRows(5);
        jTextArea5.setText("Ataque de inyeccion de SQL,\nCódigo SQL, código SQL malicioso,\nAplicacion web, Acceso no autorizado.");
        jScrollPane5.setViewportView(jTextArea5);

        btnReporInyecSql.setBackground(new java.awt.Color(60, 78, 234));
        btnReporInyecSql.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporInyecSql.setForeground(new java.awt.Color(0, 0, 0));
        btnReporInyecSql.setText("Reportar");
        btnReporInyecSql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporInyecSqlActionPerformed(evt);
            }
        });

        txtNumAtaquesInyecSql.setBackground(new java.awt.Color(254, 43, 43));
        txtNumAtaquesInyecSql.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtNumAtaquesInyecSql.setForeground(new java.awt.Color(0, 0, 0));
        txtNumAtaquesInyecSql.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumAtaquesInyecSql.setText("0");
        txtNumAtaquesInyecSql.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Ataques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumAtaquesInyecSql.setCaretColor(new java.awt.Color(254, 43, 43));
        txtNumAtaquesInyecSql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAtaquesInyecSqlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReporInyecSql, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNumAtaquesInyecSql, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporInyecSql, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAtaquesInyecSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(232, 232, 232));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ransomware");

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea2.setRows(5);
        jTextArea2.setText("WannaCry, Petya, Ryuk\nCifrado, Rescate, Malware.");
        jScrollPane2.setViewportView(jTextArea2);

        btnReporRansomware.setBackground(new java.awt.Color(60, 78, 234));
        btnReporRansomware.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporRansomware.setForeground(new java.awt.Color(0, 0, 0));
        btnReporRansomware.setText("Reportar");
        btnReporRansomware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporRansomwareActionPerformed(evt);
            }
        });

        txtNumAtaquesRanso.setBackground(new java.awt.Color(254, 43, 43));
        txtNumAtaquesRanso.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtNumAtaquesRanso.setForeground(new java.awt.Color(0, 0, 0));
        txtNumAtaquesRanso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumAtaquesRanso.setText("0");
        txtNumAtaquesRanso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Ataques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumAtaquesRanso.setCaretColor(new java.awt.Color(254, 43, 43));
        txtNumAtaquesRanso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAtaquesRansoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReporRansomware, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNumAtaquesRanso, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporRansomware, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAtaquesRanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );

        jPanel6.setBackground(new java.awt.Color(232, 232, 232));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Phishing");

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea3.setRows(5);
        jTextArea3.setText("Spear phishing, Vishing,\nCorreo electrónico, Engaño,\nInformacion confidencial.");
        jScrollPane3.setViewportView(jTextArea3);

        btnReporPhishin.setBackground(new java.awt.Color(60, 78, 234));
        btnReporPhishin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporPhishin.setForeground(new java.awt.Color(0, 0, 0));
        btnReporPhishin.setText("Reportar");
        btnReporPhishin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporPhishinActionPerformed(evt);
            }
        });

        txtNumAtaquesPhish.setBackground(new java.awt.Color(254, 43, 43));
        txtNumAtaquesPhish.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtNumAtaquesPhish.setForeground(new java.awt.Color(0, 0, 0));
        txtNumAtaquesPhish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumAtaquesPhish.setText("0");
        txtNumAtaquesPhish.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Ataques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumAtaquesPhish.setCaretColor(new java.awt.Color(254, 43, 43));
        txtNumAtaquesPhish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAtaquesPhishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReporPhishin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumAtaquesPhish, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumAtaquesPhish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporPhishin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel7.setBackground(new java.awt.Color(232, 232, 232));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Malware");

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea6.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea6.setRows(5);
        jTextArea6.setText("Virus, Gusanos, Troyanos,\nSoftware malicioso, Daño,\nExplotacion.");
        jScrollPane6.setViewportView(jTextArea6);

        btnReporMalware.setBackground(new java.awt.Color(60, 78, 234));
        btnReporMalware.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporMalware.setForeground(new java.awt.Color(0, 0, 0));
        btnReporMalware.setText("Reportar");
        btnReporMalware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporMalwareActionPerformed(evt);
            }
        });

        txtNumAtaquesMalwa.setBackground(new java.awt.Color(254, 43, 43));
        txtNumAtaquesMalwa.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtNumAtaquesMalwa.setForeground(new java.awt.Color(0, 0, 0));
        txtNumAtaquesMalwa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumAtaquesMalwa.setText("0");
        txtNumAtaquesMalwa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Ataques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumAtaquesMalwa.setCaretColor(new java.awt.Color(254, 43, 43));
        txtNumAtaquesMalwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAtaquesMalwaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReporMalware, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNumAtaquesMalwa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporMalware, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAtaquesMalwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        jPanel8.setBackground(new java.awt.Color(232, 232, 232));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DDoS");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Ataque a Dyn, Mirai botnet,\nTrafico falso, Inaccesibilidad,\nServicio en linea.");
        jScrollPane1.setViewportView(jTextArea1);

        btnReporDdos.setBackground(new java.awt.Color(60, 78, 234));
        btnReporDdos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporDdos.setForeground(new java.awt.Color(0, 0, 0));
        btnReporDdos.setText("Reportar");
        btnReporDdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporDdosActionPerformed(evt);
            }
        });

        txtNumAtaquesDdos.setBackground(new java.awt.Color(254, 43, 43));
        txtNumAtaquesDdos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtNumAtaquesDdos.setForeground(new java.awt.Color(0, 0, 0));
        txtNumAtaquesDdos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumAtaquesDdos.setText("0");
        txtNumAtaquesDdos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Ataques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumAtaquesDdos.setCaretColor(new java.awt.Color(254, 43, 43));
        txtNumAtaquesDdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAtaquesDdosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReporDdos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumAtaquesDdos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel4))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporDdos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAtaquesDdos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(232, 232, 232));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Zero-Day Exploit");

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea7.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea7.setRows(5);
        jTextArea7.setText("Stuxnet, Vulnerabilidades,\nSeguridad, Explotación, Parche.");
        jScrollPane7.setViewportView(jTextArea7);

        btnReporZeroDay.setBackground(new java.awt.Color(60, 78, 234));
        btnReporZeroDay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporZeroDay.setForeground(new java.awt.Color(0, 0, 0));
        btnReporZeroDay.setText("Reportar");
        btnReporZeroDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporZeroDayActionPerformed(evt);
            }
        });

        txtNumAtaquesZeroDay.setBackground(new java.awt.Color(254, 43, 43));
        txtNumAtaquesZeroDay.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtNumAtaquesZeroDay.setForeground(new java.awt.Color(0, 0, 0));
        txtNumAtaquesZeroDay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumAtaquesZeroDay.setText("0");
        txtNumAtaquesZeroDay.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Ataques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumAtaquesZeroDay.setCaretColor(new java.awt.Color(254, 43, 43));
        txtNumAtaquesZeroDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAtaquesZeroDayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReporZeroDay, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNumAtaquesZeroDay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporZeroDay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAtaquesZeroDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        jPanel10.setBackground(new java.awt.Color(232, 232, 232));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Hacking Dispositivo IoT");

        jTextArea11.setEditable(false);
        jTextArea11.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea11.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea11.setRows(5);
        jTextArea11.setText("Ataques a cámaras de seguridad,\ndispositivos domesticos inteligentes,\nAcceso no autorizado.");
        jScrollPane11.setViewportView(jTextArea11);

        btnReporHacking.setBackground(new java.awt.Color(60, 78, 234));
        btnReporHacking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporHacking.setForeground(new java.awt.Color(0, 0, 0));
        btnReporHacking.setText("Reportar");
        btnReporHacking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporHackingActionPerformed(evt);
            }
        });

        txtNumAtaquesHacking.setBackground(new java.awt.Color(254, 43, 43));
        txtNumAtaquesHacking.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtNumAtaquesHacking.setForeground(new java.awt.Color(0, 0, 0));
        txtNumAtaquesHacking.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumAtaquesHacking.setText("0");
        txtNumAtaquesHacking.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Ataques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumAtaquesHacking.setCaretColor(new java.awt.Color(254, 43, 43));
        txtNumAtaquesHacking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAtaquesHackingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReporHacking, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNumAtaquesHacking, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane11)
                    .addContainerGap()))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumAtaquesHacking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporHacking, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        jPanel11.setBackground(new java.awt.Color(232, 232, 232));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Violacion de Datos");

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea4.setRows(5);
        jTextArea4.setText("Equifax, Yahoo, LinkedIn,\nAcceso no autorizado,\nInformacion personal, Credenciales.");
        jScrollPane4.setViewportView(jTextArea4);

        btnReporVioDatos.setBackground(new java.awt.Color(60, 78, 234));
        btnReporVioDatos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporVioDatos.setForeground(new java.awt.Color(0, 0, 0));
        btnReporVioDatos.setText("Reportar");
        btnReporVioDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporVioDatosActionPerformed(evt);
            }
        });

        txtNumAtaquesViolaDatos.setBackground(new java.awt.Color(254, 43, 43));
        txtNumAtaquesViolaDatos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtNumAtaquesViolaDatos.setForeground(new java.awt.Color(0, 0, 0));
        txtNumAtaquesViolaDatos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumAtaquesViolaDatos.setText("0");
        txtNumAtaquesViolaDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Ataques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumAtaquesViolaDatos.setCaretColor(new java.awt.Color(254, 43, 43));
        txtNumAtaquesViolaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAtaquesViolaDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReporVioDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumAtaquesViolaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporVioDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAtaquesViolaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );

        jPanel12.setBackground(new java.awt.Color(232, 232, 232));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ataque Infraestructura Críticas");

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea8.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea8.setRows(5);
        jTextArea8.setText("Energía, Agua, Transporte,\nInfraestructuras esenciales,\ncompromiso.");
        jScrollPane8.setViewportView(jTextArea8);

        btnReporInfraCriticas.setBackground(new java.awt.Color(60, 78, 234));
        btnReporInfraCriticas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporInfraCriticas.setForeground(new java.awt.Color(0, 0, 0));
        btnReporInfraCriticas.setText("Reportar");
        btnReporInfraCriticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporInfraCriticasActionPerformed(evt);
            }
        });

        txtNumAtaquesInfraCriti.setBackground(new java.awt.Color(254, 43, 43));
        txtNumAtaquesInfraCriti.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtNumAtaquesInfraCriti.setForeground(new java.awt.Color(0, 0, 0));
        txtNumAtaquesInfraCriti.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumAtaquesInfraCriti.setText("0");
        txtNumAtaquesInfraCriti.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Ataques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumAtaquesInfraCriti.setCaretColor(new java.awt.Color(254, 43, 43));
        txtNumAtaquesInfraCriti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAtaquesInfraCritiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(btnReporInfraCriticas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumAtaquesInfraCriti, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane8)
                    .addContainerGap()))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporInfraCriticas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAtaquesInfraCriti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        jPanel13.setBackground(new java.awt.Color(232, 232, 232));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Espionaje Cibernético");

        jTextArea12.setEditable(false);
        jTextArea12.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextArea12.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea12.setRows(5);
        jTextArea12.setText("Amenazas persistentes avanzadas,\nAPT, Gobiernos, Organizaciones, \nInformación sensible.");
        jScrollPane12.setViewportView(jTextArea12);

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Reportar");

        btnReporCibernetico.setBackground(new java.awt.Color(60, 78, 234));
        btnReporCibernetico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporCibernetico.setForeground(new java.awt.Color(0, 0, 0));
        btnReporCibernetico.setText("Reportar");
        btnReporCibernetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporCiberneticoActionPerformed(evt);
            }
        });

        txtNumAtaquesCiberneti.setBackground(new java.awt.Color(254, 43, 43));
        txtNumAtaquesCiberneti.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtNumAtaquesCiberneti.setForeground(new java.awt.Color(0, 0, 0));
        txtNumAtaquesCiberneti.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumAtaquesCiberneti.setText("0");
        txtNumAtaquesCiberneti.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Ataques", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNumAtaquesCiberneti.setCaretColor(new java.awt.Color(254, 43, 43));
        txtNumAtaquesCiberneti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAtaquesCibernetiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReporCibernetico, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNumAtaquesCiberneti, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporCibernetico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAtaquesCiberneti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );

        btnRegresarMenu.setBackground(new java.awt.Color(60, 78, 234));
        btnRegresarMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresarMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarMenu.setText("Menu");
        btnRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuActionPerformed(evt);
            }
        });

        btnRegresarMenu1.setBackground(new java.awt.Color(60, 78, 234));
        btnRegresarMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresarMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarMenu1.setText("Salir");
        btnRegresarMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(jLabel1)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresarMenu)
                        .addGap(29, 29, 29)
                        .addComponent(btnRegresarMenu1)
                        .addGap(17, 17, 17)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRegresarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRegresarMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int ContRans, ContPhis, ContDdos, ContVioDat, ContInyecSql, ContMalwa, ContZero, ContInfra, ContRedes, ContInfoCon, ContHack, ContCiber;
    
    private void txtNumAtaquesRansoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAtaquesRansoActionPerformed
                     
    }//GEN-LAST:event_txtNumAtaquesRansoActionPerformed
        
    private void btnReporRansomwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporRansomwareActionPerformed
        ContRans ++;
        String numero = String.valueOf(ContRans);
        txtNumAtaquesRanso.setText(numero);
    }//GEN-LAST:event_btnReporRansomwareActionPerformed

    private void txtNumAtaquesPhishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAtaquesPhishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAtaquesPhishActionPerformed

    private void btnReporPhishinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporPhishinActionPerformed
        ContPhis ++;
        String numero = String.valueOf(ContPhis);
        txtNumAtaquesPhish.setText(numero);
    }//GEN-LAST:event_btnReporPhishinActionPerformed

    private void txtNumAtaquesHackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAtaquesHackingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAtaquesHackingActionPerformed

    private void txtNumAtaquesViolaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAtaquesViolaDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAtaquesViolaDatosActionPerformed

    private void txtNumAtaquesDdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAtaquesDdosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAtaquesDdosActionPerformed

    private void txtNumAtaquesCibernetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAtaquesCibernetiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAtaquesCibernetiActionPerformed

    private void txtNumAtaquesInfoConfidenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAtaquesInfoConfidenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAtaquesInfoConfidenActionPerformed

    private void txtNumAtaquesMalwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAtaquesMalwaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAtaquesMalwaActionPerformed

    private void txtNumAtaquesInfraCritiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAtaquesInfraCritiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAtaquesInfraCritiActionPerformed

    private void txtNumAtaquesInyecSqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAtaquesInyecSqlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAtaquesInyecSqlActionPerformed

    private void txtNumAtaquesZeroDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAtaquesZeroDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAtaquesZeroDayActionPerformed

    private void txtNumAtaquesRedesSociaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAtaquesRedesSociaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAtaquesRedesSociaActionPerformed

    private void btnReporHackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporHackingActionPerformed
        ContHack ++;
        String numero = String.valueOf(ContHack);
        txtNumAtaquesHacking.setText(numero);
    }//GEN-LAST:event_btnReporHackingActionPerformed

    private void btnReporDdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporDdosActionPerformed
        ContDdos ++;
        String numero = String.valueOf(ContDdos);
        txtNumAtaquesDdos.setText(numero);
    }//GEN-LAST:event_btnReporDdosActionPerformed

    private void btnReporVioDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporVioDatosActionPerformed
        ContVioDat ++;
        String numero = String.valueOf(ContVioDat);
        txtNumAtaquesViolaDatos.setText(numero);
    }//GEN-LAST:event_btnReporVioDatosActionPerformed

    private void btnReporInyecSqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporInyecSqlActionPerformed
        ContInyecSql ++;
        String numero = String.valueOf(ContInyecSql);
        txtNumAtaquesInyecSql.setText(numero);
    }//GEN-LAST:event_btnReporInyecSqlActionPerformed

    private void btnReporMalwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporMalwareActionPerformed
        ContMalwa ++;
        String numero = String.valueOf(ContMalwa);
        txtNumAtaquesMalwa.setText(numero);
    }//GEN-LAST:event_btnReporMalwareActionPerformed

    private void btnReporZeroDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporZeroDayActionPerformed
        ContZero ++;
        String numero = String.valueOf(ContZero);
        txtNumAtaquesZeroDay.setText(numero);
    }//GEN-LAST:event_btnReporZeroDayActionPerformed

    private void btnReporInfraCriticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporInfraCriticasActionPerformed
        ContInfra ++;
        String numero = String.valueOf(ContInfra);
        txtNumAtaquesInfraCriti.setText(numero);
    }//GEN-LAST:event_btnReporInfraCriticasActionPerformed

    private void btnReporRedesSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporRedesSocialActionPerformed
        ContRedes ++;
        String numero = String.valueOf(ContRedes);
        txtNumAtaquesRedesSocia.setText(numero);
    }//GEN-LAST:event_btnReporRedesSocialActionPerformed

    private void btnReporInfoConfidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporInfoConfidencialActionPerformed
        ContInfoCon ++;
        String numero = String.valueOf(ContInfoCon);
        txtNumAtaquesInfoConfiden.setText(numero);
    }//GEN-LAST:event_btnReporInfoConfidencialActionPerformed

    private void btnReporCiberneticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporCiberneticoActionPerformed
        ContCiber ++;
        String numero = String.valueOf(ContCiber);
        txtNumAtaquesCiberneti.setText(numero);
    }//GEN-LAST:event_btnReporCiberneticoActionPerformed

    private void btnRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuActionPerformed
        Menu RegresarMenu = new Menu();
        RegresarMenu.setVisible(true);
        RegresarMenu.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegresarMenuActionPerformed

    private void btnRegresarMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenu1ActionPerformed
        Login SalirLogin = new Login();
        SalirLogin.setVisible(true);
        SalirLogin.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegresarMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarMenu;
    private javax.swing.JButton btnRegresarMenu1;
    private javax.swing.JButton btnReporCibernetico;
    private javax.swing.JButton btnReporDdos;
    private javax.swing.JButton btnReporHacking;
    private javax.swing.JButton btnReporInfoConfidencial;
    private javax.swing.JButton btnReporInfraCriticas;
    private javax.swing.JButton btnReporInyecSql;
    private javax.swing.JButton btnReporMalware;
    private javax.swing.JButton btnReporPhishin;
    private javax.swing.JButton btnReporRansomware;
    private javax.swing.JButton btnReporRedesSocial;
    private javax.swing.JButton btnReporVioDatos;
    private javax.swing.JButton btnReporZeroDay;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField txtNumAtaquesCiberneti;
    private javax.swing.JTextField txtNumAtaquesDdos;
    private javax.swing.JTextField txtNumAtaquesHacking;
    private javax.swing.JTextField txtNumAtaquesInfoConfiden;
    private javax.swing.JTextField txtNumAtaquesInfraCriti;
    private javax.swing.JTextField txtNumAtaquesInyecSql;
    private javax.swing.JTextField txtNumAtaquesMalwa;
    private javax.swing.JTextField txtNumAtaquesPhish;
    private javax.swing.JTextField txtNumAtaquesRanso;
    private javax.swing.JTextField txtNumAtaquesRedesSocia;
    private javax.swing.JTextField txtNumAtaquesViolaDatos;
    private javax.swing.JTextField txtNumAtaquesZeroDay;
    // End of variables declaration//GEN-END:variables
}
